apiVersion: provisioning.grafana.app/v0alpha1
kind: Repository
metadata:
  name: git-sync-default
spec:
  title: Git Sync Default
  type: github
  github:
    url: https://github.com/${GITHUB_REPO}
    branch: ${GITHUB_BRANCH}
    path: scenario-1-default/grafana
    generateDashboardPreviews: true
  sync:
    enabled: true
    intervalSeconds: 60
    target: folder
  workflows:
    - write
    - branch
secure:
  token:
    value: ${GITHUB_PAT}
